### ISSUE TITLE
Crypric error message when using the calculator

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [Forecaster/RailcraftCalculatorFuel#1]
When using any fuel and not selecting an amount you get the cryptic message `Error 7: error.noFuel (0)` even though a fuel is selected. The reason this message shows is because the fuel amount is set to zero. A clearer error message should be implemented.

**Comment by Forecaster** [comment]
This repo is not for the calculator itself. It has it's own bugtracker built into the comment system.
